server:
 port: 8080
 
spring:    
  # use data.sql and schema.sql ONLY when using H2 database
  # data-{platform}.sql"
 sql:
   init:
     platform: h2

 jpa:
   show-sql: true
    
   # please use Pascal_Case so you don't need this:
   hibernate:
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     ddl-auto: none