
server:
 port: 8080
 servlet:
  session:
    cookie:
      http-only: true
      secure: true
 
spring:    
  # use data.sql and schema.sql ONLY when using H2 database
  # data-{platform}.sql"
   datasource:
    url: jdbc:mysql://localhost:3306/logistics
    username: root
    password: root

   jpa:
    show-sql: true
    
   # please use Pascal_Case so you don't need this:
    hibernate:
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     ddl-auto: none
